name: Deploy ext

on:
  push:
    branches:
      - master

jobs:
  build_zip_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create Zip File - dist
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./dist.zip ./dist
      - uses: actions/upload-artifact@master
          with:
            name: dist
            path: dist-zip