name: Deploy ext

on:
  push:
    branches:
      - master

jobs:
  build_zip_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: mkdir test-zip
      - uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./test-zip/test.zip ./test
      - uses: actions/upload-artifact@master
        with:
          name: test
          path: test-zip
