name: Deploy ext

on:
  push:
    branches:
      - master

jobs:
  build_zip_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          filename: "dist.zip"
          path: "./dist"
